name: OwlServer
version: 0.1.0.0
github: "Owl/OwlServer"
license: Private
author: "Kikumoto"
maintainer: "c1155208@cstu.nit.ac.jp"
copyright: "2018 Kikumoto"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://gitlab.com/Aripiprazole/owlServer#readme>

dependencies:
  - base >= 4.7 && < 5
  - persistent
  - persistent-mongoDB
  - persistent-template
  - servant
  - servant-server
  - template-haskell
  - transformers
  - text
  - network
  - mtl
  - wai
  - wai-extra
  - wai-app-static
  - warp
  - extensible
  - lens
  - resourcet
  - cryptonite
  - bcrypt
  - entropy
  - bytestring
  - base64-bytestring
  - vector
  - aeson
  - memory
  - filepath
  - directory
  - time
  - http-types
  - file-embed

library:
  source-dirs: src

executables:
  OwlServer:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - OwlServer
      - wai-logger
      - yaml
  ApiDocs:
    main: Main.hs
    source-dirs: app/api
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - OwlServer
      - servant-docs

tests:
  OwlServer-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - OwlServer
      - QuickCheck
      - hspec
      - hspec-wai
  OwlServer-doctest:
    main: DocTest.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - OwlServer
      - doctest
      - doctest-discover
